### ISSUE TITLE
confused regarding linux instalation

### ISSUE THREAD

**Issue by user12xxxxxx** [abhi16180/photon#116]
do i need to setup flutter and android sdk to make this app?

**Comment by abhi16180** [comment]
> do i need to setup flutter and android sdk to make this app?

@user12xxxxxx You don't need flutter SDK to run the app, just extract the zip file and launch "Photon" to run it. If you want to build the app from source code then you will need flutter SDK.

**Comment by user12xxxxxx** [comment]
but i still dont get no appicon or shortcut

**Comment by abhi16180** [comment]
@user12xxxxxx let me know if its working fine now.
