### ISSUE TITLE
can't share linux to android (hyprland)

### ISSUE THREAD

**Issue by user12xxxxxx** [abhi16180/photon#117]
![240109_01h05m18s_screenshot](https://github.com/abhi16180/photon/assets/111512589/f1fae808-0153-42fa-9d3c-73fcfd61fc33)
it stays on this screen for few min and then returns to the homescreen (i can share android to linux)

**Comment by DeadSecTr** [comment]
Can't verifiy that...for me works everything fine with app and linux prog.

**Comment by user12xxxxxx** [comment]
@DeadSecTr  do i need to grant some permission to the executable file(photon)

**Comment by DeadSecTr** [comment]
For me works out of the box...

There is no "settings" to check to work

**Comment by user12xxxxxx** [comment]
is it a DE thing?
what DE are you using?

**Comment by DeadSecTr** [comment]
Ubuntu 22.04 lts

**Comment by abhi16180** [comment]
@user12xxxxxx This screen is shown when native file picker is invoked. If there is no permission to access file system it will freeze at this phase. Please check if necessary permissions are given.

**Comment by user12xxxxxx** [comment]
![240110_12h38m42s_screenshot](https://github.com/abhi16180/photon/assets/111512589/af1c3989-359d-4158-a81f-29596d19a05c)
i think it has necessary permission.

**Comment by user12xxxxxx** [comment]
so i asked this same question in distro community and they said it probably has something to do with hyprland
so @abhi16180 should i close this issue?

**Comment by abhi16180** [comment]
> so i asked this same question in distro community and they said it probably has something to do with hyprland
> so @abhi16180 should i close this issue?
> 

@user12xxxxxx Yes, since it is not specific to photon this can be closed.
