### ISSUE TITLE
How to package photon-windows-release-v2.0.0.exe on Windows?

### ISSUE THREAD

**Issue by GanZhiXiong** [abhi16180/photon#122]
I have a question. I am a Make newbie. I want to package an installation package, but I don't know where to start.

There are innoinstall, inno, and choco in the Makefile. These configurations should be related to Windows. I don't know the difference between them and don't know which command to use.

Looking forward to your reply. Thank you very much!

**Comment by GanZhiXiong** [comment]
@abhi16180 
Can you help me? Thank you so much!

**Comment by abhi16180** [comment]
Hi @GanZhiXiong , please checkout [this](https://github.com/abhi16180/photon/blob/main/photon_inst.iss) file. This is a script where you can provider whatever config you want for your application and you can run it on inno setup application to create a package. 
You can refer [this](https://www.c-sharpcorner.com/UploadFile/tunturu/installer-using-inno-setup/) doc as well.

**Comment by GanZhiXiong** [comment]
@abhi16180 Thank you very much for your reply!
If I want to generate a Windows application installation package locally through the make command, which command should I execute?

I don't know whether it is `make innoinstall` or `make inno` or `make choco`, or other commands. What is the difference between them?

**Comment by abhi16180** [comment]
@GanZhiXiong 
Inno and choco (chocolatey) are mostly used for packaging windows applications. 
In my Makefile,
- `make innoinstall` is used for installing the inno setup on system.
- `make inno` is used for packaging the application with inno setup
- `make choco` is used for packaging the application with chocolatey

But I am not using above cmds in my workflow.

If you want to build installation package with inno, you can use the below command. Replace it with Installation path of Inno Setup and your inno script file.

`"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" yourscript.iss`

**Comment by GanZhiXiong** [comment]
@abhi16180 
Thank you for your detailed answer. I finally figured it out.
