### ISSUE TITLE
add linux build

### ISSUE THREAD

**Issue by TheMonocledHamster** [abhi16180/photon#13]

**Comment by MesterPerfect** [comment]
Coming soon

**Comment by Rayrsn** [comment]
update?

**Comment by abhi16180** [comment]
> update?

Linux build for v1.0.0 is already available. But due to some issues I couldn't publish linux builds for v1.0.1 and v1.0.2.
Currently I am working on it and future versions will include linux build. Meanwhile you can check out linux build v1.0.0.
