### ISSUE TITLE
More accessibility with screen readers

### ISSUE THREAD

**Issue by MesterPerfect** [abhi16180/photon#14]
hi
I'm a blind user and I'm trying to use photon with nvda screen reader
Using the keyboard I can't press the 'Share' or 'Receive' button
I can only press the 'Open navigation menu' button
can you help me?

**Comment by abhi16180** [comment]
Hello, I am sorry to inform you that this app is not fully compatible with "nvda" yet , I will definitely check If I can fully implement it in next version.

**Comment by MesterPerfect** [comment]
> Hello, I am sorry to inform you that this app is not fully compatible with "nvda" yet , I will definitely check If I can fully implement it in next version.

the problem is not very complicated, just make the save and share buttons focusable, as you did with the navigation menu button.
the focus with keyboard can done by using the ws_TabStop style or one of its equivalents

**Comment by abhi16180** [comment]
> > Hello, I am sorry to inform you that this app is not fully compatible with "nvda" yet , I will definitely check If I can fully implement it in next version.
> 
> the problem is not very complicated, just make the save and share buttons focusable, as you did with the navigation menu button. the focus with keyboard can done by using the ws_TabStop style or one of its equivalents

Yeah , I am gonna check it out soon.

**Comment by MesterPerfect** [comment]
> > > Hello, I am sorry to inform you that this app is not fully compatible with "nvda" yet , I will definitely check If I can fully implement it in next version.
> > 
> > 
> > the problem is not very complicated, just make the save and share buttons focusable, as you did with the navigation menu button. the focus with keyboard can done by using the ws_TabStop style or one of its equivalents
> 
> Yeah , I am gonna check it out soon.

ok
