### ISSUE TITLE
wrong versionName/versionCode in v1.0.1

### ISSUE THREAD

**Issue by IzzySoft** [abhi16180/photon#19]
The APK attached to v1.0.1 still identifies as v1.0.0 (and `versionCode: 1`) – looks like you forgot to [update `pubspec.yaml`](https://github.com/abhi16180/photon/blob/main/pubspec.yaml#L18). For v1.0.1, the linked line should read

```yaml
version: 1.0.1+2
```

Just in case: the first part is what's shown to the users (which might now be confused, thinking they got an old APK). The second part, following the `+`, is what Android uses internally to tell versions apart and to decide if it should notify about or even automatically install an update. Currently, Android would consider v1.0.1 to be ignored as it is still v1.0.0 :scream: so it's important to always increase `versionCode` when making a new release.

Could you please take care to update this with future releases? Thanks a lot!

**Comment by abhi16180** [comment]
Thank you so much for pointing this out. Will definitely add proper versionCode in future updates.

**Comment by abhi16180** [comment]
> The APK attached to v1.0.1 still identifies as v1.0.0 (and `versionCode: 1`) – looks like you forgot to [update `pubspec.yaml`](https://github.com/abhi16180/photon/blob/main/pubspec.yaml#L18). For v1.0.1, the linked line should read
> 
> ```yaml
> version: 1.0.1+2
> ```
> 
> Just in case: the first part is what's shown to the users (which might now be confused, thinking they got an old APK). The second part, following the `+`, is what Android uses internally to tell versions apart and to decide if it should notify about or even automatically install an update. Currently, Android would consider v1.0.1 to be ignored as it is still v1.0.0 :scream: so it's important to always increase `versionCode` when making a new release.
> 
> Could you please take care to update this with future releases? Thanks a lot!

Thank you so much for pointing this out. Will definitely add proper versionCode in future updates.

**Comment by IzzySoft** [comment]
Thanks! By the way, your app is currently listed [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.example.photon) – if you want to link there e.g. from the Readme, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for a "graphical eye-catcher". And if you're open to have your app listed by [F-Droid](https://f-droid.org/) itself: I think it meets the inclusion criteria (my repo often serves as stepping stone to figure this and get apps ready for it). No pressure or something like that, just a pointer :smile:

**Comment by IzzySoft** [comment]
Thanks for adding the badge – and great to read you consider heading for F-Droid! F-Droid then would strongly prefer if metadata (description, screenshots etc) where available via [Fastlane structures](https://gitlab.com/-/snippets/1895688) in the app's repo. As I've set that up on my end already, I gladly provide you what I have here as a "starter package" to build on, e.g. via PR. Just let me know if you'd want me to send it, and I'll do.

**Comment by abhi16180** [comment]
> Thanks for adding the badge – and great to read you consider heading for F-Droid! F-Droid then would strongly prefer if metadata (description, screenshots etc) where available via [Fastlane structures](https://gitlab.com/-/snippets/1895688) in the app's repo. As I've set that up on my end already, I gladly provide you what I have here as a "starter package" to build on, e.g. via PR. Just let me know if you'd want me to send it, and I'll do.

Thanks a lot for showing interest in this project. Currently I am working on adding some more features to this app. So It may take some time before publishing it to F-Droid. If I face any issue related to meta-data I will reach you out .

**Comment by IzzySoft** [comment]
Great, wish you good progress then!

**Comment by abhi16180** [comment]
> Great, wish you good progress then!

Thank you 😀!

**Comment by abhi16180** [comment]
@IzzySoft  Hello ,
I have published new version (v1.0.2) with GPL3 license. Your repo is showing MIT license. Can you please change it to GPL3?

**Comment by IzzySoft** [comment]
@abhi16180 done, effective with the next sync (around 6 pm UTC, as usual).

**Comment by abhi16180** [comment]
> @abhi16180 done, effective with the next sync (around 6 pm UTC, as usual).

Thank you so much.

**Comment by abhi16180** [comment]
@IzzySoft Hey I have released latest version with some changes to app name and application ID. So it seems your repo didn't recognize it as update to older version. Is there any way to fix it ?

**Comment by IzzySoft** [comment]
A different ApplicationId means a different app – so it has to be added again like any new app. I [already did that](https://apt.izzysoft.de/fdroid/index/apk/dev.abhi.photon) (and amended the description of the old AppId with a hint linking to the new) – apologies for the delay, I was on vacation. Giving a little overlap, I'll remove the listing of the old ApplicationId.

**Comment by abhi16180** [comment]
> A different ApplicationId means a different app – so it has to be added again like any new app. I [already did that](https://apt.izzysoft.de/fdroid/index/apk/dev.abhi.photon) (and amended the description of the old AppId with a hint linking to the new) – apologies for the delay, I was on vacation. Giving a little overlap, I'll remove the listing of the old ApplicationId.

Thanks a lot.

**Comment by IzzySoft** [comment]
No prob. You probably had to rename as Playstore does not accept apps with `com.example.*` names :wink:
