### ISSUE TITLE
Add landscape rotation on android app

### ISSUE THREAD

**Issue by cyanwolfg** [abhi16180/photon#29]
App works pretty good but in large screens like tablets the app force to portrait mode.
Thanks for all your work!

**Comment by abhi16180** [comment]
> App works pretty good but in large screens like tablets the app force to portrait mode. Thanks for all your work!

Yeah app is intentionally constrained to portrait mode (in mobile devices) , as app isn't fully responsive yet. In the next update, app will be more responsive and support both portrait / landscape mode. Thank you for using the app 😊.
