### ISSUE TITLE
Sharing windows to Android

### ISSUE THREAD

**Issue by heberjeur** [abhi16180/photon#37]
Hi, I can't send any files from windows to Android phone, but I can send from android to windows, it have been recognized, I tried via modem transfer and via hotspot, it's the same!

**Comment by abhi16180** [comment]
> Hi, I can't send any files from windows to Android phone, but I can send from android to windows, it have been recognized, I tried via modem transfer and via hotspot, it's the same!

Hey thank you for letting me know about this. But I have published the app after testing it on windows and android.
Can you please install and try this  version and report if it is working for you .
[Photon-dev-build](https://github.com/abhi16180/photon/releases/download/nightly/photon-windows-nightly.exe)
Please reply whether this version worked for you.

**Comment by heberjeur** [comment]
Hey @abhi16180 , it doesn't work for me, can you send a debug version if you want, I use Samsung A50 and Dell with windows 10 21H2

**Comment by abhi16180** [comment]
> Hey @abhi16180 , it doesn't work for me, can you send a debug version if you want, I use Samsung A50 and Dell with windows 10 21H2

 Its difficult to identify the issue unless we run in debug mode. Its not possible with  executable file. Can you clarify the issue?
 Is there issue with device discovery ?
 Or file transfer process stops at 0.0 percent?

**Comment by heberjeur** [comment]
It's related to device discovery, my Android doesn't receive any signal from my PC, I think that there are problem with windows services

![Screenshot_20220918-161806](https://user-images.githubusercontent.com/11852634/190914552-d0b34581-ab29-4027-abd3-e2ed65f66e8c.jpg)

**Comment by abhi16180** [comment]
> It's related to device discovery, my Android doesn't receive any signal from my PC, I think that there are problem with windows services
> 
> ![Screenshot_20220918-161806](https://user-images.githubusercontent.com/11852634/190914552-d0b34581-ab29-4027-abd3-e2ed65f66e8c.jpg)

This may happen when you first click on receive button  even before the sharing process starts. Have you tried clicking sharing button on windows first before tapping receive button on android and still facing the same issue ? If so ,I will have to look into the code once.

**Comment by heberjeur** [comment]
> > It's related to device discovery, my Android doesn't receive any signal from my PC, I think that there are problem with windows services
> > ![Screenshot_20220918-161806](https://user-images.githubusercontent.com/11852634/190914552-d0b34581-ab29-4027-abd3-e2ed65f66e8c.jpg)
> 
> This may happen when you first click on receive button even before the sharing process starts. Have you tried clicking sharing button on windows first before tapping receive button on android and still facing the same issue ? If so ,I will have to look into the code once.

Yes of course I tried it.

**Comment by abhi16180** [comment]
> > > It's related to device discovery, my Android doesn't receive any signal from my PC, I think that there are problem with windows services
> > > ![Screenshot_20220918-161806](https://user-images.githubusercontent.com/11852634/190914552-d0b34581-ab29-4027-abd3-e2ed65f66e8c.jpg)
> > 
> > 
> > This may happen when you first click on receive button even before the sharing process starts. Have you tried clicking sharing button on windows first before tapping receive button on android and still facing the same issue ? If so ,I will have to look into the code once.
> 
> Yes of course I tried it.

I will look into it.

**Comment by cyanwolfg** [comment]
@heberjeur I noticed you are using a VPN, I have had problems trying to connect devices on the same network with the VPN active, have you tried disabling it when sending files?

**Comment by heberjeur** [comment]
I used Netguard,I tested with and without it, I have the same result

**Comment by abhi16180** [comment]
I have tested it on windows 11 ,its working properly. I will try it out on windows 10 soon.

**Comment by saracenz21** [comment]
Is it possible to without installation of the pc app? In Xender we can upload files to Android from pc from the webview without any external app

**Comment by abhi16180** [comment]
> Is it possible to without installation of the pc app? In Xender we can upload files to Android from pc in the webview without any external app

For now app doesn't allow that. It requires photon to be installed on both devices. It was designed so because photon was intended to be truly cross platform without any requirements for extern clients like browser.
Maybe in future versions it will be added as an option.

**Comment by abhi16180** [comment]
> I used Netguard,I tested with and without it, I have the same result

Please check if you have installed virtual box on your machine, it alters network interface settings and photon won't be able to locate the exact ip for serving files.

**Comment by abhi16180** [comment]
> I have the same problem, I am using Invizible pro which is a firewall and i allowed LAN only for your app sir and on pc iam using Portmaster which btw didn't give me any alert of using internet so great job, Anyway the problem for me isn't solved unfortunately so i will try and use the dev version of the app
> 
> P.s Iam testing the app if it is completely local as iam someone who is sharing content about privacy and security and if i was wrong about anything and someone find this app using Internet by any means ,I will be fired

Try using the latest version of Android and windows.


Note: This app neither collects user data nor it sends data over the internet. Also  data transfer happens only when you choose to do so. Everything happens within LAN. (*No encryption*)
