### ISSUE TITLE
How can I help with translation?

### ISSUE THREAD

**Issue by cyanwolfg** [abhi16180/photon#38]
Hi, I don't know a lot of programming but I help with some translations into spanish on other open-source android apps on github but I don't know if this is possible on this project and what I need to do.

**Comment by abhi16180** [comment]
> Hi, I don't know a lot of programming but I help with some translations into spanish on other open-source android apps on github but I don't know if this is possible on this project and what I need to do.

Hey thank you for showing interest, but I am currently focused on fixing existing bugs and issues. So translation process may take bit longer. I haven't implemented any sort of internationalization yet.
