### ISSUE TITLE
Documentation: Where does the asset go?

### ISSUE THREAD

**Issue by mrmetaverse** [abhi16180/photon#39]
Good morning, I am sure this is a total noob question but I need help. Can we add to the README where you can find the files you are transfering? I cannot find the video I sent from my android to my arch PC. Its not in the program files, its not in downloads or recents, not in images or videos, and I can't find it in the /tmp folder. 

The app has a "history" of transfers but no method of clicking to go to that file or even see the files properties to guess where it may have landed.

**Comment by abhi16180** [comment]
> Good morning, I am sure this is a total noob question but I need help. Can we add to the README where you can find the files you are transfering? I cannot find the video I sent from my android to my arch PC. Its not in the program files, its not in downloads or recents, not in images or videos, and I can't find it in the /tmp folder.
> 
> The app has a "history" of transfers but no method of clicking to go to that file or even see the files properties to guess where it may have landed.

Hi there, currently app doesn't allow user to set file-location. But before sharing process starts it will show the file-storing location. I have set downloads folder as file-storing location.
![Screenshot_2022-09-23-19-35-42-39_c740c744050a0025d8a70725a6d71073](https://user-images.githubusercontent.com/64468853/191979449-8515f71c-51b7-4f6e-a996-61c5ece3c39b.jpg)

You can see the location here.
You should be able to see your files in downloads location no matter whichever device you are using.
If you are not able to find files , can you please tell me the device that you are using ?

**Comment by mrmetaverse** [comment]
Oh ok, that helped. I have a pixel6 running grapheneOs. The computer I was using for this exercise is the razer 14" AMD (with the ryzen and a NVIDIA 3070). I can also test on my main machine later but should all work now :) 

I will submit a PR with documentation update

**Comment by abhi16180** [comment]
> Oh ok, that helped. I have a pixel6 running grapheneOs. The computer I was using for this exercise is the razer 14" AMD (with the ryzen and a NVIDIA 3070). I can also test on my main machine later but should all work now :)
> 
> I will submit a PR with documentation update

Cool. Are you able to locate your files now?
