### ISSUE TITLE
:bug: no UI rendering (Arch)

### ISSUE THREAD

**Issue by mrmetaverse** [abhi16180/photon#47]
What I expected: 
![image](https://user-images.githubusercontent.com/63426722/192348859-3031a4ed-6c1f-46d9-88ef-545b10e179b3.png)

What I got: 
![image](https://user-images.githubusercontent.com/63426722/192348819-88102c90-f4d2-4a72-8990-6589be1e7279.png)

```
[mrmetaverse@UFO photon]$ sudo su
UFO /home/mrmetaverse/Github/photon # flutter pub get packages
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Running "flutter pub get" in ....                               1,016ms⣽
UFO /home/mrmetaverse/Github/photon # flutter run 
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                          ⣽

** (Photon:256853): WARNING **: 14:04:29.110: Failed to start Flutter renderer: Unable to create a GL context
```

**Comment by mrmetaverse** [comment]
I will add that the old version does still work.

**Comment by abhi16180** [comment]
@mrmetaverse 
Please check if this works for you
`flutter run --enable-software-rendering`

**Comment by mrmetaverse** [comment]
@abhi16180 that worked! Want me to submit another PR with updated documentation or maybe a FAQ section?

**Comment by abhi16180** [comment]
> @abhi16180 that worked! Want me to submit another PR with updated documentation or maybe a FAQ section?

yeah !
