### ISSUE TITLE
Can't transfer file fro Android to macOs

### ISSUE THREAD

**Issue by giuseppe99barchetta** [abhi16180/photon#52]
<img width="792" alt="Schermata 2022-09-30 alle 14 01 02" src="https://user-images.githubusercontent.com/55151669/193265147-ccd6ba70-5ca8-41d2-b880-7cba388c01ed.png">

When i try to transfer file from Android 13 on Pixel 6 to macOs monterey on macbook Pro m1 the status say "cancelled"

**Comment by abhi16180** [comment]
> <img alt="Schermata 2022-09-30 alle 14 01 02" width="792" src="https://user-images.githubusercontent.com/55151669/193265147-ccd6ba70-5ca8-41d2-b880-7cba388c01ed.png">
> 
> When i try to transfer file from Android 13 on Pixel 6 to macOs monterey on macbook Pro m1 the status say "cancelled"

I have tested it on intel mac, its working on it. There must be some issue with writing permission. I don't have m1 mac with me right now , I will try to figure out the solution soon.

**Comment by abhi16180** [comment]
@giuseppe99barchetta 

Finally, found the solution. You just have to go to settings and allow photon to access docs and downloads folder. 
![image](https://user-images.githubusercontent.com/64468853/211563841-3dad9d84-aeb7-4a88-a94e-a93a030d5393.png)

Please send a mail or reply here if this solution is working for you.
