### ISSUE TITLE
When transfering videos whit emoji it fails to transfer

### ISSUE THREAD

**Issue by FedericoSlongo** [abhi16180/photon#53]
It failded whit all the videos I've tried to transef
![image](https://user-images.githubusercontent.com/73640124/195380824-7e263aa5-6007-4904-b046-e9f08e304de3.png)

**Comment by abhi16180** [comment]
> It failded whit all the videos I've tried to transef ![image](https://user-images.githubusercontent.com/73640124/195380824-7e263aa5-6007-4904-b046-e9f08e304de3.png)
Hey I have been working on that issue since past 2 weeks, please check this version (development version) and please let me know if this is working for you.
https://github.com/abhi16180/photon/releases/download/nightly/photon-android-nightly.apk

**Comment by abhi16180** [comment]
> It didn't work Also I'm transferring from android to windows ![image](https://user-images.githubusercontent.com/73640124/195589149-271811a2-06cb-442e-9e44-f5e98a2c70d3.png)

Okay ,there must be issue with file path because of emojis. Will look into it.
