### ISSUE TITLE
Thank you, brilliant*

### ISSUE THREAD

**Issue by inspector71** [abhi16180/photon#54]
This app transfers photos from my Android phone to my Windows laptop, when both are on the same wifi network.

WOW :)

Sensational!

Superb. 

You have no idea how simple that need is, but how incredibly difficult it has hitherto been to solve.

I love it.

Absolutely brilliant with one small, slight caveat: a context menu option to "Open Containing Folder" would be perfection.

Would love to contribute that myself though my development skills are limited and so far do not include Dart, Flutter, etc. However, having seen this example of an app that _**finally**_ connects my phone well to Windows, without being stuck in a browser at the receiving end which just feels a little compromised, unfortunately, I'm definitely more motivated now to try my hand at Dart/Flutter etc.

Otherwise the sensational minimalism, simplicity and usability is so very good, I'll be taking a backup of the current version just in case further development might dilute that slightly or massively :) Most software goes that way, sadly.

**Comment by abhi16180** [comment]
@inspector71 Thank you for appreciating the project.

Can you elaborate what do you mean by ,
"Open Containing Folder"?
