### ISSUE TITLE
Photon crashes in Windows 7(version 1.2.0)

### ISSUE THREAD

**Issue by c-sanchez** [abhi16180/photon#88]
Hi, I am running Windows 7 Home Basic x64, when I start Photon 1.2.0 the program crashes.![Photon 1.2.0 Windows 7](https://i.ibb.co/xSsLRqV/photon120.jpg)

Photon 1.1.0 starts without any problems.
![Photon 1.1.0 Windows 7](https://i.ibb.co/5kPYh5m/photon110.jpg)

**Comment by abhi16180** [comment]
@c-sanchez Can you please send exact error message in English?

**Comment by c-sanchez** [comment]
@abhi16180 The error message doesn't really say much
> A problem caused the program to stop working correctly. Close the program

Btw, I just noticed that it says "Problem" twice, which doesn't make sense (Windows translation error?) 
> El **problema** dejó de funcionar correctamente por un **problema**. Cierre el programa
The problem stopped working properly because of a problem. Close the program.

**Comment by c-sanchez** [comment]
If you want you can send me a debug version that generates a report to see what happens

**Comment by abhi16180** [comment]
> If you want you can send me a debug version that generates a report to see what happens

There is no "crash logs" or "analytics" related code in app. So it's not possible to get any reports. I think there is some issue with dll or some dependencies. Check  the bundle version (.zip) once, as it contains all dependencies.

**Comment by c-sanchez** [comment]
It was the zip version that I used heh.
I just tried with the installer, and after installing Photon, the exact same thing happens.

**Comment by abhi16180** [comment]
> It was the zip version that I used heh. I just tried with the installer, and after installing Photon, the exact same thing happens.

Woa, I don't have win 7 device with me, but will try to find solution.

**Comment by c-sanchez** [comment]
> > It was the zip version that I used heh. I just tried with the installer, and after installing Photon, the exact same thing happens.
> 
> Woa, I don't have win 7 device with me, but will try to find solution.

hehe ok, let me know if you have any version you want me to try :)

**Comment by abhi16180** [comment]
> > > It was the zip version that I used heh. I just tried with the installer, and after installing Photon, the exact same thing happens.
> > 
> > 
> > Woa, I don't have win 7 device with me, but will try to find solution.
> 
> hehe ok, let me know if you have any version you want me to try :)

If possible, try to install flutter SDK on your machine and clone this repo and try to run the app. If it crashes on "run", do send the snapshot of the terminal.

**Comment by c-sanchez** [comment]
Hi @abhi16180 I downloaded the flutter sdk, but I have no knowledge of how to compile or run anything from flutter
Do I need anything else? like cmake, vscode?

If there is a simple way to run/compile the repository with flutter sdk and a bat file that would be great.

**Comment by abhi16180** [comment]
> Hi @abhi16180 I downloaded the flutter sdk, but I have no knowledge of how to compile or run anything from flutter
> Do I need anything else? like cmake, vscode?
> 
> If there is a simple way to run/compile the repository with flutter sdk and a bat file that would be great.

You need visual studio code installed on your machine for developing flutter windows apps. You can edit it using any editor. But for development you can install the libraries from visual studio code set-up. But I don't think flutter supports windows 7 development

**Comment by abhi16180** [comment]
Windows 7 is not part of flutter supported devices
