### ISSUE TITLE
Unable to transfer between android and windows 11.

### ISSUE THREAD

**Issue by onthejobtraining** [abhi16180/photon#91]
I was trying to send files from my android 11 phone to windows 11 laptop and I got this cancelled
![message](https://user-images.githubusercontent.com/75716685/218302996-5937d157-b4e0-4216-8bc3-505c8781a6f2.png)

And when I tried to send files from windows to android, I got "No device found" message on the android app while using both QRCode and Normal Mode. 

The laptop is connected to the android's mobile hotspot and files permission is given.

**Comment by abhi16180** [comment]
This usually happens if you do not allow app to bypass firewall. Please check it once.

**Comment by abhi16180** [comment]
> This usually happens if you do not allow app to bypass firewall. Please check it once.

@metronightly

**Comment by metronightly** [comment]
> @metronightly This usually happens if you do not allow app to bypass firewall. Please check it once.

Okay, firewall seems fine and I even successfully transferred images (jpg and png) from android to windows but for some reason the video files are showing the cancelled error.

**Comment by abhi16180** [comment]
> 

Okay, that's weird !!. Will check it out
