### ISSUE TITLE
SocketException: Failed to create server socket

### ISSUE THREAD

**Issue by SerpoDark** [abhi16180/photon#93]
When i was first using the desktop app the software is working normally. But now somehow Photon won't connect with my phone and i got this error message. I don't know what's wrong. It was working fine before

PC: Windows 10
Phone: Android 11

**Comment by abhi16180** [comment]
> When i was first using the desktop app the software is working normally. But now somehow Photon won't connect with my phone and i got this error message. I don't know what's wrong. It was working fine before
> 
> PC: Windows 10
> Phone: Android 11


@SerpoDark 
Please make sure that you are connected to wifi or hotspot is turned on.

**Comment by SerpoDark** [comment]
> > When i was first using the desktop app the software is working normally. But now somehow Photon won't connect with my phone and i got this error message. I don't know what's wrong. It was working fine before
> > PC: Windows 10
> > Phone: Android 11
> 
> @SerpoDark Please make sure that you are connected to wifi or hotspot is turned on. Also you cannot run 2 photon app instances simultaneously on the desktop.

Thank you for the response. I have turned on the wifi and tried the Hotspot too. The error message is gone now somehow. But my phone still can't find my pc to receive file. I have checked that only one Photon is running. I'm sorry, i'm not familiar with programming world so i'm confused about it.

**Comment by abhi16180** [comment]
> > > When i was first using the desktop app the software is working normally. But now somehow Photon won't connect with my phone and i got this error message. I don't know what's wrong. It was working fine before
> > > PC: Windows 10
> > > Phone: Android 11
> > 
> > @SerpoDark Please make sure that you are connected to wifi or hotspot is turned on. Also you cannot run 2 photon app instances simultaneously on the desktop.
> 
> Thank you for the response. I have turned on the wifi and tried the Hotspot too. The error message is gone now somehow. But my phone still can't find my pc to receive file. I have checked that only one Photon is running. I'm sorry, i'm not familiar with programming world so i'm confused about it.

Follow these steps

1. Make sure your phone and laptop are connected to the same wifi.

2. Or try to turn-on your mobile hotspot, connect your laptop to your mobile hotspot. Then start sharing/ receiving. 

If you follow one of these steps it will definitely work.

Please respond with whether everything is working.

**Comment by SerpoDark** [comment]
So these are the steps that i have been tried to solve the problem


1. Using the same wifi network from a router [Failed]
2. Using Laptop hotspot [Failed]
3. Using Phone mobile hotspot [Failed]
4. Tried to change the wifi status to private for better discovery [Failed]

But somehow if i try to tranfer a file from smartphone to desktop it's working fine. My Pc can detect the incoming tranfer. The only problem is when i tried to tranfer file from Pc to my phone. Photon just won't find my incoming pc tranfer. 

![Screenshot_20230219_145417](https://user-images.githubusercontent.com/123316339/219936577-fe7b3c67-9c98-4094-b8eb-b8940966eefa.jpg)

**Comment by abhi16180** [comment]
> So these are the steps that i have tried to solve the problem. 
> I'm not turning two photon apps at the same time nor turning wifi and hotspot simultaneously.
> 
> 1. Using the same wifi network from a router [Failed]
> 2. Using Laptop hotspot [Failed]
> 3. Using Phone mobile hotspot [Failed]
> 4. Tried to change the wifi status to private for better discovery [Failed]
> 5. Reinstall Photon Desktop [Failed]
> 6. Restarting PC [Failed]
> 
> But somehow if i try to tranfer a file from smartphone to desktop it's working fine. My Pc can detect the incoming tranfer. The only problem is when i tried to tranfer file from Pc to my phone. Photon just won't find my incoming pc tranfer. 
> 
> ![Screenshot_20230219_145417](https://user-images.githubusercontent.com/123316339/219936577-fe7b3c67-9c98-4094-b8eb-b8940966eefa.jpg)
> 

Please try QR scan mode

**Comment by SerpoDark** [comment]
> > So these are the steps that i have tried to solve the problem.
> > I'm not turning two photon apps at the same time nor turning wifi and hotspot simultaneously.
> > 
> > 1. Using the same wifi network from a router [Failed]
> > 2. Using Laptop hotspot [Failed]
> > 3. Using Phone mobile hotspot [Failed]
> > 4. Tried to change the wifi status to private for better discovery [Failed]
> > 5. Reinstall Photon Desktop [Failed]
> > 6. Restarting PC [Failed]
> > 
> > But somehow if i try to tranfer a file from smartphone to desktop it's working fine. My Pc can detect the incoming tranfer. The only problem is when i tried to tranfer file from Pc to my phone. Photon just won't find my incoming pc tranfer.
> > ![Screenshot_20230219_145417](https://user-images.githubusercontent.com/123316339/219936577-fe7b3c67-9c98-4094-b8eb-b8940966eefa.jpg)
> 
> Please try QR scan mode

yes i also tried QR method. Still nothing happened. I'm sorry, maybe this problem in particular only affecting my pc. If i can remember correctly about yesterday my Windows got an update. Maybe that what causing this to happen. It was very good before and i love this app.

**Comment by abhi16180** [comment]
@SerpoDark I am not sure about issue. The last suggestion from me is, make sure you allow photon to bypass firewall on desktop.
